import type { Metadata } from "next";
import { Gabarito, Poppins, Geist } from "next/font/google";
import { LanguageProvider } from "@/components/LanguageProvider";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const gabarito = Gabarito({
  variable: "--font-gabarito",
  subsets: ["latin"],
  weight: ["700", "800"], // Bold focused
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${gabarito.variable} ${poppins.variable} antialiased font-secondary`}
      >
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
