export const COUNTRY_CODES = [
    { code: "+57", country: "Colombia", flag: "🇨🇴" },
    { code: "+1", country: "USA", flag: "🇺🇸" },
    { code: "+34", country: "España", flag: "🇪🇸" },
    { code: "+52", country: "México", flag: "🇲🇽" },
    { code: "+54", country: "Argentina", flag: "🇦🇷" },
    { code: "+56", country: "Chile", flag: "🇨🇱" },
    { code: "+51", country: "Perú", flag: "🇵🇪" },
    { code: "+58", country: "Venezuela", flag: "🇻🇪" },
    { code: "+507", country: "Panamá", flag: "🇵🇦" },
    { code: "+506", country: "Costa Rica", flag: "🇨🇷" },
    { code: "+1", country: "Puerto Rico", flag: "🇵🇷" },
    { code: "+593", country: "Ecuador", flag: "🇪🇨" },
    { code: "+591", country: "Bolivia", flag: "🇧🇴" },
    { code: "+502", country: "Guatemala", flag: "🇬🇹" },
    { code: "+503", country: "El Salvador", flag: "🇸🇻" },
    { code: "+504", country: "Honduras", flag: "🇭🇳" },
    { code: "+505", country: "Nicaragua", flag: "🇳🇮" },
    { code: "+598", country: "Uruguay", flag: "🇺🇾" },
    { code: "+595", country: "Paraguay", flag: "🇵🇾" },
    { code: "+1", country: "Rep. Dominicana", flag: "🇩🇴" },
]
